# Generated by Django 3.2.12 on 2022-02-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'verbose_name': 'изображение места', 'verbose_name_plural': 'изображения мест'},
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(verbose_name='краткое описание'),
        ),
    ]
