# Generated by Django 3.2.12 on 2022-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220204_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position'], 'verbose_name': 'изображение места', 'verbose_name_plural': 'изображения мест'},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
